node:
  replicas: 1

  image:
    repository: thedin87/pizza-express
    tag: latest
    pullPolicy: Always
  
  requests:
    cpu: 200m
    memory: 32Mi
  
  limits:
    cpu: 250m
    memory: 64Mi

  ingress:
    enabled: true

  logToFile:
    enabled: false

redis:
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent

  requests:
    cpu: 100m
    memory: 100Mi
  
  limits:
    cpu: 1
    memory: 200Mi

