apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      app: pizza-express
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pizza-express
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: pizza-express
        image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}"
        imagePullPolicy: {{ .Values.node.image.pullPolicy }}
        env:
          - name: REDIS_URL
            value: "redis://{{ .Release.Name }}-redis:6379"
        resources:
          limits:
            memory: {{ .Values.node.limits.memory}}
            cpu: {{ .Values.node.limits.cpu}}
          requests:
            memory: {{ .Values.node.requests.memory }}
            cpu: {{ .Values.node.requests.cpu }}
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: pizza-express
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 3000