 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: {{ .Release.Name }}
   namespace: {{ .Release.Namespace }}
 spec:
  rules:
  - host: {{ .Release.Name }}.piz.za
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.name }}
            port:
              number: 8081
  ingressClassName: nginx