apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: redis
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: master
        image: "{{ .Values.redis.image.repository}}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        resources:
          limits:
            memory: {{ .Values.redis.limits.memory }}
            cpu: {{ .Values.redis.limits.cpu }}
          requests:
            memory: {{ .Values.redis.requests.memory }}
            cpu: {{ .Values.redis.requests.cpu }}
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    release: {{ .Release.Name }}