apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: redis
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: master
        image: registry.k8s.io/redis:e2e
        resources:
          limits:
            memory: {{ ne .Values.redis.limits.memory "200Mi" }}
            cpu: {{ ne .Values.redis.limits.cpu "1" }}
          requests:
            memory: {{ ne .Values.redis.requests.memory "100Mi" }}
            cpu: {{ ne .Values.redis.requests.cpu "100m" }}
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    aapp: redis
    release: {{ .Release.Name }}