name: Docker Image CI

on:
  push:
    branches: [ "**_rc" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5services:

    env:
      REDIS_URL: "redis://localhost:6379"
    
    steps:
    - uses: actions/checkout@v4

    - id: commit
      uses: prompt/actions-commit-hash@v3

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - name: Install npm packages
      run: npm install

    - name: Do the ci tests
      run: npm test

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: thedin87/pizza-express:${{ github.ref }}-${{ steps.commit.outputs.short }}
        cache-from: type=registry,ref=thedin87/pizza-express:buildcache
        cache-to: type=registry,ref=thedin87/pizza-express:buildcache,mode=max

    - name: Run the image with env variable
      run:  docker run -dit -e REDIS_URL="redis://localhost:6379" -p 3000:3000 thedin87/pizza-express:${{ github.ref }}-${{ steps.commit.outputs.short }}

    - name: curl localhost:3000 
      run: curl --connect-timeout 100 http://localhost:3000

    - name: push image to registry
      run: docker push thedin87/pizza-express:${{ github.ref }}-${{ steps.commit.outputs.short }}
    
      

