on:
  
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: get version from package.json
      run: export APP_VERSION=$(cat package.json | grep version | awk -F '"' '{ print $4 }')

    - run: echo ${{ env.APP_VERSION }}

    - name: Build
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        load: true
        tags: thedin87/pizza-express:${{ env.APP_VERSION }}
        cache-from: type=registry,ref=thedin87/pizza-express:buildcache
        cache-to: type=registry,ref=thedin87/pizza-express:buildcache,mode=max
